name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-20.04'
        python-version:
          - '3.8'
        arch:
          - 'x86_64'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Dependencies
      run: |
        sudo python -m pip install --upgrade pip && sudo apt-get install -y language-pack-en curl
        export LC_CTYPE=en_US.UTF-8
        sudo apt-get -y install locales 
        curl -sSL https://install.python-poetry.org | python3 -
        poetry config virtualenvs.in-project true
        timeout 10s poetry run pip --version || rm -rf .venv
        poetry install
        poetry run pip install pytest-github-actions-annotate-failures
        python -m pip install --upgrade pip
        pip install black
        
    - name: test      
      run: |
        export BBB_TEST_LOCATIONS='' 
        ./test.sh

  armv64_job:
    name: Build and Test for arm64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Install and Run tests
        run: |
           docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
             arm64v8/ubuntu:20.04 \
              bash -exc 'apt-get update && apt-get -y install git python3 python3-pip curl && apt-get install -y language-pack-en && export LC_CTYPE=en_US.UTF-8 && apt-get -y install locales && \
              python3 -m pip install --upgrade pip && \
              pip3 install boostedblob && \
              curl -sSL https://install.python-poetry.org | python3 - && \
              pip3 install poetry && \
              poetry install && \
              pip3 install black && \
              BBB_TEST_LOCATIONS='' ./test.sh && \
              deactivate'
